### ISSUE TITLE
UI layout structure

### ISSUE THREAD

**Issue by arnaucube** [iden3/iden3-playground#8]
Proposal to new UI layout organization:

- 2 main columns
    - left: Wallet stuff
        - wallet tab
            - identity creation
            - keys creation
        - backup tab
        - settings tab
    - right: Actions. Divided in tabs for each kind of action / backend server
        - Emit claims (in the user's identity tree)
        - Name server & name resolver
        - Sign & Login
        - Notifications
        - tx-forwarder
        - zkProofs

plus a foldable side panel, that appears when user clicks over the semi hidden button

main concept:
```
+----------------------------------------------+
|Top menu bar                                  |
+----------------------------------------------+
|tabs...       |tabs...                        |
+----------------------------------------------+
|              |                               |
|Left column   |   Right column                |
|              |                        +------+
|              |                        |show  |
|              |                        |side  |
|              |                        |panel |
|              |                        |button|
|              |                        +------+
|              |                               |
|              |                               |
|              |                               |
|              |                               |
+--------------+-------------------------------+
```

**Comment by krlosMata** [comment]
Good redistribution of playground. Seems nice for me xD
